language: generic
sudo: required
services:
   - docker

before_install:
   - docker build -t sswaminath/react-test -f ./client/Dockerfile.dev ./client

script:

  - docker run -e CI=true sswaminath/react-test npm test

after_success:
   - docker build -t sswaminath/multi-client ./client
   - docker build -t sswaminath/multi-nginx  ./nginx
   - docker build -t  sswaminath/multi-server ./server
   - docker build -t sswaminath/multi-worker ./worker

   #Push images to Docker Hub
   - echo "$DOCKER_PASSWORD" |docker login -u "$DOCKER_ID" --password-stdin
   - docker push sswaminath/multi-client
   - docker push sswaminath/multi-nginx
   - docker push sswaminath/multi-server
   - docker push sswaminath/multi-worker